name: Linux and MacOS tests

permissions:
  contents: read

on: [ push, pull_request ]

jobs:


  macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          # macos-14 runs on aarch64; the others run on x64
          - macos-12
          # - macos-13
          # - macos-14
        CMAKE_ARGS:
          - -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_BUILD_TYPE="Debug" -DOQS_MINIMAL_BUILD="KEM_kyber_768;SIG_cross_rsdp_128_small;SIG_cross_rsdp_128_small_avx2"
          # - -DOQS_HAZARDOUS_EXPERIMENTAL_ENABLE_SIG_STFL_KEY_SIG_GEN=ON -DOQS_ENABLE_SIG_STFL_XMSS=ON -DOQS_ENABLE_SIG_STFL_LMS=ON
          # - -DOQS_USE_OPENSSL=OFF
          # - -DBUILD_SHARED_LIBS=ON -DOQS_DIST_BUILD=OFF
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # pin@v5
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Install dependencies
        run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja && pip3 install --require-hashes --break-system-packages -r .github/workflows/requirements.txt
      - name: Patch GCC
        run: env HOMEBREW_NO_AUTO_UPDATE=1 brew uninstall --ignore-dependencies gcc@13 && wget https://raw.githubusercontent.com/Homebrew/homebrew-core/eb6dd225d093b66054e18e07d56509cf670793b1/Formula/g/gcc%4013.rb && env HOMEBREW_NO_AUTO_UPDATE=1 brew install --ignore-dependencies --formula gcc@13.rb
      - name: Get system information
        run: sysctl -a | grep machdep.cpu
      - name: Configure
        run: mkdir -p build && cd build && source ~/.bashrc && cmake -GNinja -DOQS_STRICT_WARNINGS=ON ${{ matrix.CMAKE_ARGS }} .. && cmake -LA -N ..
      - name: Build
        run: ninja
        working-directory: build
      - name: a--------------------------------------------------------------a
        #run: cat src/sig/cross/upcross_cross-rsdp-128-small_clean/CROSS.c
        run: ./build/tests/test_sig cross-rsdp-128-small
        working-directory: build/..
      - name: Run tests
        run: mkdir -p tmp && python3 -m pytest -x --verbose --ignore=tests/test_code_conventions.py --ignore=tests/test_kat_all.py ${{ matrix.PYTEST_ARGS }}
        timeout-minutes: 60

